# Site settings
title: 
header-img: img/home-bg.png
email: ho.tonym@gmail.com
copyright_name: ho-tonym
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ho-tonym
learn_profile: ho-tonym
email_username: ho.tonym@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
